ignore:
  - ".github"
  - "go.mod"
  - "go.sum"

coverage:
  precision: 2
  round: down
  range: "85..100"
  status:
    project:
      default:
        target: auto
        threshold: 0%
        base: auto
        if_ci_failed: error
