ignore:
  - ".github"
  - "go.mod"
  - "go.sum"
  - "testing_helpers.go"

coverage:
  range: "85..100"
  round: down
  precision: 2
  status:
    project:
      default:
        target: auto
        threshold: 0%
        base: auto
