name: Go Test

on: push

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup GO env
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'
          cache: true
      - name: Run Unit Tests
        run: go test -v -coverprofile=coverage.txt
      - name: Upload coverage to CodeCov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          verbose: true